
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcdydebdzloygiqkxruc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjZHlkZWJkemxveWdpcWt4cnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NzI3NTUsImV4cCI6MjA1OTE0ODc1NX0.idZsCQ6p3RO1Lk-xDntXpjB6FvamY0qHF_Bza-JnDJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
